  server:
    port: 8080

  spring:
    application:
      name: syprome

    datasource:
      username: 'dev'
      password: 'Test@243'
      url: jdbc:mariadb://34.68.248.132:3306/syprome
      hikari:
        minimum-idle: 10
        maximum-pool-size: 10000
        idle-timeout: 120000
        max-lifetime: 500000


    jpa:
      properties:
        dialect: org.mariadb.jdbc.Driver

      hibernate:
        ddl-auto: update
      show-sql: true
    mail:
      host: 10.25.3.122
      port: 25
      properties.mail.smtp:
        auth: false

    servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB



  allowedOrigins: '*'

  directions: DG,DJAR,Finances,DRH,DAL,DMC,B2B,DEC,OM,DST,DVD,DRSI,GRAND KASAI ,GRAND KATANGA ,GRAND KIVU ,GRAND NORD ,KINSHASA ,KONGO CENTRAL
  logging:
    file:
       name: syprome.log
       path: /

  myapp:
    smsUrl: http://10.25.3.81:3010/
    delay: 5
